---
  extends: airbnb-base
  env:
    node: true
    es6: true
    jest: true
  parserOptions:
    sourceType: strict
  rules:
    global-require: 0
    arrow-parens:
      - 2
      - always
    class-methods-use-this: 0
    comma-dangle:
      - error
      - never
    func-names: 0
    generator-star-spacing:
      - 2
      - before: true
        after: true
    max-len:
      - 2
      - 170
      - 2
    no-confusing-arrow: 0
    no-console: 0
    no-param-reassign: 0
    no-shadow: 0
    no-underscore-dangle: 0
    no-unused-expressions: 0
    no-use-before-define: 0
    no-plusplus: 0
    prefer-arrow-callback: 1
    require-yield: 0

    # import
    import/newline-after-import: 0
    import/no-extraneous-dependencies:
      - 2
      - devDependencies: true
    import/order:
      - error
      - newlines-between: ignore